export const sharedTemplates: Record<string, string> = {
  "package.json": `{
  "name": "{{slug state.name}}-portfolio",
  "type": "module",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "deploy": "astro build && wrangler deploy",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/cloudflare": "^13.0.0",
    "@astrojs/mdx": "^4.0.0",
    "@astrojs/sitemap": "^3.2.0",
    "@tailwindcss/vite": "^4.0.0",
    "astro": "^6.1.9",
    "tailwindcss": "^4.0.0",
    "tw-animate-css": "^1.4.0"
  },
  "devDependencies": {
    "@biomejs/biome": "^1.9.0",
    "@types/node": "^22.0.0",
    "wrangler": "^3.80.0"
  },
  "engines": {
    "node": ">=22.0.0"
  }
}
`,

  "astro.config.mjs": `import { defineConfig } from "astro/config";
import cloudflare from "@astrojs/cloudflare";
import sitemap from "@astrojs/sitemap";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  site: "https://{{state.domain}}",
  output: "server",
  adapter: cloudflare({
    imageService: "compile",
  }),
  integrations: [sitemap()],
  vite: {
    plugins: [tailwindcss()],
  },
});
`,

  "tsconfig.json": `{
  "extends": "astro/tsconfigs/strict",
  "include": [".astro/types.d.ts", "**/*"],
  "exclude": ["dist"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  }
}
`,

  "wrangler.jsonc": `{
  "name": "{{slug state.name}}-portfolio",
  "compatibility_date": "2025-01-01",
  "compatibility_flags": ["nodejs_compat"],
  "main": "./dist/_worker.js/index.js",
  "assets": {
    "directory": "./dist",
    "binding": "ASSETS"
  }
}
`,

  "biome.jsonc": `{
  "$schema": "https://biomejs.dev/schemas/1.9.0/schema.json",
  "formatter": { "enabled": true, "indentStyle": "space", "indentWidth": 2 },
  "linter": {
    "enabled": true,
    "rules": { "recommended": true }
  }
}
`,

  ".gitignore": `# build
dist/
.astro/

# deps
node_modules/

# logs
npm-debug.log*
pnpm-debug.log*
yarn-debug.log*

# environment
.env
.env.production
.dev.vars

# editors
.vscode/
.idea/
.DS_Store

# wrangler
.wrangler/
`,

  ".assetsignore": `_worker.js
_routes.json
`,

  "src/content.config.ts": `import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const projects = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/projects" }),
  schema: z.object({
    title: z.string(),
    summary: z.string(),
    stack: z.array(z.string()).default([]),
    role: z.string().optional(),
    date: z.string().optional(),
    liveUrl: z.string().optional(),
    repoUrl: z.string().optional(),
    cover: z.string().optional(),
    order: z.number().default(0),
  }),
});

export const collections = { projects };
`,

  "src/env.d.ts": `/// <reference path="../.astro/types.d.ts" />
`,

  "public/favicon.svg": `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="currentColor"/><text x="16" y="22" font-family="Georgia,serif" font-size="20" text-anchor="middle" fill="#fff">{{xml state.name.[0]}}</text></svg>
`,

  "README.md": `# {{state.name}} — Portfolio

Personal portfolio site for {{state.name}}, {{state.role}}{{#if state.location}}, based in {{state.location}}{{/if}}.

Built with Astro 6, Tailwind v4, and Cloudflare Workers. Generated with [Forge](https://forge.zacgibson.work).

## Quick start

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

Visit http://localhost:4321.

## Editing your content

| What | Where |
|---|---|
| Hero text | \`src/pages/index.astro\` |
| Projects | \`src/content/projects/*.md\` |
| Site config | \`astro.config.mjs\` |
| Color tokens | \`src/styles/global.css\` |

## Deployment

See [DEPLOY.md](./DEPLOY.md) for full Cloudflare deploy instructions.

## Stack

- [Astro 6](https://astro.build) — framework
- [Cloudflare Workers](https://workers.cloudflare.com) — hosting
- [Tailwind CSS v4](https://tailwindcss.com) — styling
- Native View Transitions
- Content Collections — Markdown-driven content

## License

The code in this repository was generated by Forge and is licensed to you, the owner, under the MIT License.

---

Built by Zac Gibson — https://zacgibson.work
`,

  "DEPLOY.md": `# Deploy your portfolio to Cloudflare Workers

This guide takes you from zip → live site at \`https://{{state.domain}}\` in about 5 minutes.

## Prerequisites

- A Cloudflare account (free tier works) — sign up at https://dash.cloudflare.com/sign-up
- Node.js 22+ installed — https://nodejs.org
- pnpm installed — \`npm install -g pnpm\`
- A custom domain (optional — you can deploy to a \`.workers.dev\` URL first)

## Step 1 — Install dependencies

\`\`\`bash
cd portfolio
pnpm install
\`\`\`

## Step 2 — Run locally

\`\`\`bash
pnpm dev
\`\`\`

Visit http://localhost:4321. Edit content in \`src/content/\` and pages in \`src/pages/\` — changes hot-reload.

## Step 3 — Sign in to Cloudflare via Wrangler

\`\`\`bash
pnpm dlx wrangler login
\`\`\`

A browser window opens. Authorize Wrangler to access your Cloudflare account.

## Step 4 — Build and deploy

\`\`\`bash
pnpm build
pnpm wrangler deploy
\`\`\`

Wrangler outputs your live URL — looks like \`https://{{slug state.name}}-portfolio.your-account.workers.dev\`. Visit it. You're live.

## Step 5 (OPTIONAL) — Connect your custom domain

If you own \`{{state.domain}}\` and have it on Cloudflare:

1. Go to your Worker in the Cloudflare dashboard → Settings → Domains & Routes.
2. Click **Add → Custom Domain**.
3. Enter \`{{state.domain}}\` and click Add.
4. Cloudflare auto-configures DNS. Wait ~30 seconds.
5. Visit \`https://{{state.domain}}\` — it's live with a free SSL certificate.

If your domain isn't on Cloudflare:

1. In Cloudflare dashboard, click **Add a Site** and enter \`{{state.domain}}\`.
2. Cloudflare gives you two nameservers — copy them.
3. Go to your domain registrar (Namecheap, GoDaddy, Porkbun, etc.) and replace the nameservers with Cloudflare's.
4. Wait for propagation (up to 24 hours, usually under 1 hour).
5. Once Cloudflare shows the site as Active, follow the steps above.

## Editing your content

| What | Where |
|---|---|
| Hero text | \`src/pages/index.astro\` |
| Projects | \`src/content/projects/*.md\` (one file per project) |
| About page | \`src/pages/about.astro\` |
| Site config | \`astro.config.mjs\` |
| Color tokens | \`src/styles/global.css\` (under \`@theme\`) |

## Troubleshooting

**Build fails with "Cannot find module 'sharp'"** — Cloudflare Workers don't bundle sharp. Astro 6 handles image optimization at build time, so this shouldn't appear in production. If it does, ensure \`imageService: 'compile'\` is set in \`astro.config.mjs\`.

**Custom domain stays "Not Active"** — wait 30 minutes after DNS change before contacting Cloudflare support. Most issues self-resolve.

**Lighthouse score below 95** — make sure you're testing the production deploy, not local dev.

---

Generated by Forge — https://forge.zacgibson.work
`,
};

export const projectMarkdownTemplate = `---
title: "{{yamlStr title}}"
summary: "{{yamlStr summary}}"
stack: [{{#each stack}}"{{yamlStr this}}"{{#unless @last}}, {{/unless}}{{/each}}]
{{#if role}}role: "{{yamlStr role}}"
{{/if}}{{#if date}}date: "{{yamlStr date}}"
{{/if}}{{#if liveUrl}}liveUrl: "{{yamlStr liveUrl}}"
{{/if}}{{#if repoUrl}}repoUrl: "{{yamlStr repoUrl}}"
{{/if}}{{#if cover}}cover: "{{yamlStr cover}}"
{{/if}}order: {{order}}
---

{{summary}}
`;
